### ISSUE TITLE
Custom serverDefinitions not being displayed in PgAdmin console

### ISSUE THREAD

**Issue by zach-iwx** [rowanruseler/helm-charts#193]
**Describe the bug**
Custom serverDefinitions not being displayed in PgAdmin console

**Version of Helm and Kubernetes**:
Kubernetes (AKS): v1.24.9
Helm: v3.8.0

**Which chart**:
pgadmin4 (v1.14.3)

**What happened**:
Once instance has been deployed, validated that servers.json file is indeed mounted into the pod. To confirm that the output file is valid, I saved it to my local machine and was able to re-import the file with no issues. Is this a file permission problem perhaps? I tried setting 
`VolumePermissions.enabled` to true but that did not make any difference.

**What you expected to happen**:
Server should appear in the PgAdmin console

**How to reproduce it** (as minimally and precisely as possible):
Not sure exactly?

**Anything else we need to know**:

**Comment by hhorvat0305** [comment]
Any news about this one? I'm experiencing the same issue.

**Comment by rowanruseler** [comment]
I saw a weird error when I tried to reproduce the issue described here, and since @hhorvat0305 applied it is working in an older version of the chart it had to be an issue in the docker image. Searching on the error: `'AnonymousUser' object has no attribute 'username'` brought me here: https://github.com/pgadmin-org/pgadmin4/issues/5751

The issue is resolved in the latest tag, so either we wait for the 6.20 release or you adjust your values file to use the latest tag rather then 6.19 tag.

**Comment by zach-iwx** [comment]
Thanks @rowanruseler will try updating to the latest tag and report back

**Comment by smitphilip** [comment]
> The issue is resolved in the latest tag, so either we wait for the 6.20 release or you adjust your values file to use the latest tag rather then 6.19 tag.

this didn't resolve the import issue for me - i'll dig a bit more and report back

**Comment by akierat** [comment]
@smitphilip Were you able to solve the problem? Unfortunately I have the same problem

**Comment by deefdragon** [comment]
I am also encountering this issue with the servers not loading. 

Something that's managed to work for me was CLI-ing in and loading the servers via the setup.py command. The fact that that functioned implies to me that pgadmin is not attempting to load the servers, even though PGADMIN_SERVER_JSON_FILE is set, but I dont have enough experience to confirm for sure. Going to see if I can dig into the pgadmin code to find out.

**Comment by deefdragon** [comment]
From what I can see, The loading of servers should be done via [this line](https://github.com/pgadmin-org/pgadmin4/blob/8b354aec1dca4fcf0dd8efa97275e059d8b4df13/pkg/docker/entrypoint.sh#L118) in entrypoint.sh. Checking my startup logs, I dont see any output that says that that line was run however. 

I believe that is because entrypoint.sh will only run the block from L#74-132 on _first init_. (RE: `[ ! -f /var/lib/pgadmin/pgadmin4.db ]` checking for if the pgadmin.db file exists already or not.). As such, if the servers.json file is changed, or only added after the first boot, nothing gets loaded in. I suspect this is the cause of several reported bugs on PGadmin's side regarding the servers not populating.

Im going to file a bug with regards to this on PGAdmin's side and see what they think.

**Comment by deefdragon** [comment]
Regarding the servers not loading in after first init, I have a working bodge, but its not the most ideal solution as it requires using the --replace option on the load-servers command, which _removes all existing servers_, including those loaded in through the UI.

If you want to define all of your servers via the server.json however, it works well enough. 

Adding this to the extraInitContainers will cause the servers.json to be re-loaded in every boot of pgadmin
> [!CAUTION]
> Again, This will also **remove all existing servers** in the pgadmin database first, including those loaded in via the UI.
```
      - name: import-servers-json
        image: "docker.io/dpage/pgadmin4:latest"
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - |
            /venv/bin/python /pgadmin4/setup.py load-servers --user admin@streem.tech --auth-source internal --replace /pgadmin4/servers.json
        volumeMounts:
          - name: pgadmin-data
            mountPath: /var/lib/pgadmin
          - name: definitions
            mountPath: /pgadmin4/servers.json
            subPath: servers.json
        securityContext:
          runAsUser: 0
 ```
 
I'm working in the pgadmin issue referenced above to come to a solution that would not require the --replace flag, and would allow loading the list of servers on every execution.
